== Microservices

=== Definition

_Microservices are independently deployable modules_

=== What is a Microservice

Microservices are characterized by the fact that each service is individually
only a small more or less self-contained part of the application.

Ideally, a Microservice is independent, expandable, interchangeable and scalable.

The application to be implemented by a team
Professionalism is usually easy to understand and master.

Even technologically, a single service is much easier to maintain a monolith. 

Correctly implemented the application should work even when a service is not available.



So wie es scheint, bringen Microservices eine Menge Vorteile mit sich.
Allerdings kommt ein Microservice per Definition selten allein. Die
Komplexität der Anwendung verlagert sich, im Vergleich zum Monolithen,
auf das korrekte Zusammenspiel der Services. Wie also müssen die
Services geschnitten sein, um die eben aufgeführten Bedingungen –
unabhängig erweiterbar, austauschbar und skalierbar – in einer auf
Microservices basierenden, stark verteilten Architektur zu erfüllen?

=== Zentrale Eigenschaften eines Microservices

* *Nur eine Aufgabe:** Jeder Microservice ist nur für eine Aufgabe
(capability) verantwortlich. Dies solle im Normalfall eine
fachspezifische Aufgabe sein, ein Microservice kann aber auch eine
technische Aufgabe (z.B. Integration eines Umsystems) umfassen
* *Microservice besitzt seine Daten, sofern er welche verwaltet:* Dies
heisst aber nicht, dass der Microservices zwingend einen eigene
Datenbank-Instanz besitzen muss. Wichtig ist nur, dass es eine klare
Abgrenzung gibt und diese nicht umgangen werden kann (d.h. die Grenze
kann eine eigne Tabelle, ein Namensraum wie z.B. ein Schema oder aber
eine komplette Instanz sein). Dies führt zu besserer Entkoppelung, da
andere Service auf die Daten, die sie nicht besitzen nur über die
Schnittstellen zugreifen können.
* *Verantwortet Choreography und Zusammenarbeit:* Die Microservices sind
für die Choreography und die Zusammenarbeit zwischen Microservices
verantwortlich und nicht die Nachrichten-Platform dazwischen.
* *Lässt sich unabhängig ausliefern:* Jeder Microservice lässt sich
unabhängig ausliefern. Ohne dies wäre eine Microservice Applikation zur
Laufzeit weiterhin ein Monolith.
* *Lässt sich einzeln ersetzten:* Der Umfang eines Microservices soll
für jedes Teammitglied überschaubar sein und mit vertretbarem
Zeitaufwand (ca. 1 Monat) komplett neu erstellt und ersetzt werden
können.
* *Implementiert einen Bounded Context:* Ein Microservice soll einen
Bounded Context im Sinne von Domain Driven Design implementieren.
* *Von einem Team verantwortet:* Ein Microservice wird immer von einem
Team entwickelt und auch betrieben.
* *Gut isoliert:* Microservices werden gegenüber den anderen Services so
gut wie möglich isoliert
* *Nutzung des Technologie-Stack, der am Besten passt:* Ein Microservice
soll den Tec
